const roles = [
  {
    id: 1,
    name: 'player',
    createCompetitions: false,
    addGame: false,
    signUpTeam: false,
    assignTeamCaptain: false,
    assignSpiritCaptain: false,
    addAndRemovePlayers: false,
    addGameScore: false,
    addSpiritScore: false,
    readData: true,
    joinTeam: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 2,
    name: 'spirit captain',
    createCompetitions: false,
    addGame: false,
    signUpTeam: false,
    assignTeamCaptain: false,
    assignSpiritCaptain: false,
    addAndRemovePlayers: false,
    addGameScore: true,
    addSpiritScore: true,
    readData: true,
    joinTeam: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 3,
    name: 'team captain',
    createCompetitions: false,
    addGame: false,
    signUpTeam: false,
    assignTeamCaptain: true,
    assignSpiritCaptain: true,
    addAndRemovePlayers: true,
    addGameScore: true,
    addSpiritScore: true,
    readData: true,
    joinTeam: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 4,
    name: 'club board',
    createCompetitions: false,
    addGame: false,
    signUpTeam: true,
    assignTeamCaptain: true,
    assignSpiritCaptain: true,
    addAndRemovePlayers: true,
    addGameScore: true,
    addSpiritScore: true,
    readData: true,
    joinTeam: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 5,
    name: 'federation',
    createCompetitions: true,
    addGame: true,
    signUpTeam: true,
    assignTeamCaptain: true,
    assignSpiritCaptain: true,
    addAndRemovePlayers: true,
    addGameScore: true,
    addSpiritScore: true,
    readData: true,
    joinTeam: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '18021993',
    name: 'super admin',
    createCompetitions: true,
    addGame: true,
    signUpTeam: true,
    assignTeamCaptain: true,
    assignSpiritCaptain: true,
    addAndRemovePlayers: true,
    addGameScore: true,
    addSpiritScore: true,
    readData: true,
    joinTeam: true,
    createdAt: new Date(),
    updatedAt: new Date()
  }
];

module.exports = roles;
